Create tve.list on postinst

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -6,28 +6,31 @@
 set -e
 
 # summary of how this script can be called:
-#        * <postinst> `configure' <most-recently-configured-version>
-#        * <old-postinst> `abort-upgrade' <new version>
-#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
-#          <new-version>
-#        * <postinst> `abort-remove'
-#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-#          <failed-install-package> <version> `removing'
-#          <conflicting-package> <version>
+#		* <postinst> `configure' <most-recently-configured-version>
+#		* <old-postinst> `abort-upgrade' <new version>
+#		* <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#		  <new-version>
+#		* <postinst> `abort-remove'
+#		* <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#		  <failed-install-package> <version> `removing'
+#		  <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 
 case "$1" in
-    configure)
-    ;;
-    abort-upgrade|abort-remove|abort-deconfigure)
-    ;;
+	configure)
+		if [ ! -f "$TVEROOT/etc/tve.list" ]; then
+			echo "deb http://pkgs.theveeb.com/ tve games libs utils" > "$TVEROOT/etc/tve.list"
+		fi
+	;;
+	abort-upgrade|abort-remove|abort-deconfigure)
+	;;
 
-    *)
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
+	*)
+		echo "postinst called with unknown argument \`$1'" >&2
+		exit 1
+	;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
